site_name: Google Technical Writing Exercises - Ivo Sam
nav:
  - Exercise 1 — findNeedles: index.md
  - Exercise 2 — How to Play Tic-Tac-Toe: exercise2.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: 