site_name:  Ivo Sam - Writing samples
nav:
  - Sample 1 - Method reference: index.md
  - Exercise 2a — Explaining Concepts: exercise2b.md
  - Exercise 2b — How to Play Tic-Tac-Toe: exercise2.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: 